// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

 static FirebaseOptions get web => const FirebaseOptions(
  apiKey: 'API_KEY',
  authDomain: 'PROJECT_ID.firebaseapp.com',
  projectId: 'PROJECT_ID',
  storageBucket: 'PROJECT_ID.appspot.com',
  messagingSenderId: 'SENDER_ID',
  appId: 'APP_ID',
);


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGA64rFeYJFT37kDqOSQXOhIudemZekb8',
    appId: '1:369528197991:android:3399b36f10b23ea32dd5c2',
    messagingSenderId: '369528197991',
    projectId: 'aplikasi-savings',
    storageBucket: 'aplikasi-savings.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoeJPd2lX-L5TXMDNpMRvV8ifvoI5TTjY',
    appId: '1:369528197991:ios:2ff94d1ec971f4172dd5c2',
    messagingSenderId: '369528197991',
    projectId: 'aplikasi-savings',
    storageBucket: 'aplikasi-savings.firebasestorage.app',
    iosBundleId: 'com.example.savingsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoeJPd2lX-L5TXMDNpMRvV8ifvoI5TTjY',
    appId: '1:369528197991:ios:2ff94d1ec971f4172dd5c2',
    messagingSenderId: '369528197991',
    projectId: 'aplikasi-savings',
    storageBucket: 'aplikasi-savings.firebasestorage.app',
    iosBundleId: 'com.example.savingsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGnOObirPuWQbLnBbz-9mEDZz7vgVgfg8',
    appId: '1:369528197991:web:bb2d64211f9f57062dd5c2',
    messagingSenderId: '369528197991',
    projectId: 'aplikasi-savings',
    authDomain: 'aplikasi-savings.firebaseapp.com',
    storageBucket: 'aplikasi-savings.firebasestorage.app',
    measurementId: 'G-SZTK0SZ8XZ',
  );

}